name: libroteca
description: Programa para almacenar libros, valorar y puntuar.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

module:
  androidX: true
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^1.3.1
  auto_size_text: ^2.1.0
  path_provider: ^1.6.22
  cupertino_icons: ^0.1.3
  permission_handler: ^4.2.0+hotfix.3
  # open_file: ^3.0.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0

flutter_icons:
  image_path: "assets/images/libro-logo.png"
  ios: true
  android: true

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/

  fonts:
  - family: muli-extra-bold
    fonts:
    - asset: assets/fonts/Muli-ExtraBold.ttf
   
  - family: muli-black
    fonts:
    - asset: assets/fonts/Muli-Black.ttf
  - family: muli-extra-light
    fonts:
    - asset: assets/fonts/Muli-ExtraLight.ttf
  
  - family: muli-bold
    fonts:
    - asset: assets/fonts/Muli-Bold.ttf
  - family: muli-italic
    fonts:
    - asset: assets/fonts/Muli-Italic.ttf
  - family: muli-light
    fonts:
    - asset: assets/fonts/Muli-Light.ttf
  - family: muli-medium
    fonts:
    - asset: assets/fonts/Muli-Medium.ttf
  - family: muli-regular
    fonts:
    - asset: assets/fonts/Muli-Regular.ttf
  - family: muli-semi-bold
    fonts:
    - asset: assets/fonts/Muli-SemiBold.ttf

