import 'package:flutter/material.dart';

Color black = new Color(0xFF231F20);
Color red = new Color(0xffef4b4b);
Color white = Colors.white;
Color yellow = new Color(0xFFF3DFA2);
Color whiteRed = new Color(0xFFEFE6DD);
Color black20 = Colors.black.withOpacity(0.2);
Color transparent = Colors.transparent;
Color orangeLight = Color.fromARGB(255, 248, 226, 182);
Color orangeDark = Color.fromARGB(255, 243, 163, 66);
Color white24 = Colors.white24;
Color fillerGrey = Color(0xff898a8f);
Color greyText = Color(0xff707070);
Color green = Colors.green;
Color primaryColor = orangeDark;
Color primaryColorDark = orangeDark;
Color primaryColorLight = orangeLight;
Color secondaryColor = primaryColor;
Color textActiveColor = black;
Color textInactiveColor = white;
Color textSecondaryColor = greyText;
Color primaryBackgroundColor = white;
