import 'package:flutter/material.dart';

Color black = new Color(0xFF231F20);
Color red = new Color(0xffef4b4b);
Color white = Colors.white;
Color yellow = new Color(0xFFF3DFA2);
Color whiteRed = new Color(0xFFEFE6DD);
Color black20 = Colors.black.withOpacity(0.2);
Color transparent = Colors.transparent;
Color orangeLight = new Color(0xFFF9AB55);
Color orangeDark = new Color(0xFFF58A07);
Color white24 = Colors.white24;
Color fillerGrey = Color(0xff898a8f);
Color greyText = Color(0xff707070);
Color green = Colors.green;
Color primaryColor = orangeLight;
Color secondaryColor = orangeDark;
Color textActiveColor = black;
Color textInactiveColor = white;
Color textSecondaryColor = greyText;
